// CERP Project Dashboard — Tagged Dataset (Theme/Subtheme schema)
// Confidence: "confirmed" = corroborated by an independent CERP document
//             "review" = sourced only from project resume docs, needs verification
//             "untagged" = no description available, intentionally left blank
//             "schema-flag" = doesn't cleanly fit current Service Line schema
// theme/subtheme are auto-derived: Theme = union of (parent Theme of each Subtheme) + any Theme assigned directly
const PROJECTS = [

{
  id: "edu-tip-balochistan",
  name: "TIP \u2013 Balochistan Rollout",
  theme: ["Education"],
  subtheme: ["Foundational Literacy & Numeracy"],
  description: "Applied an implementation science lens across three rounds (Baseline, Midline, Endline) using teacher surveys, classroom observations, headteacher interviews, and NIETE Tech Tool data. Balochistan's public schools face acute FLN gaps. The program achieved high teacher adoption; headteacher support, teacher-led TLM innovation, and embedded coaching were key enablers.",
  partners: "Government of Balochistan, Taleemabad, CERP",
  status: "Completed",
  serviceLine: ["Program Design & Implementation Support", "Evaluations"],
  tier2: ["Process Evaluation"],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "edu-tip-ict-kpk",
  name: "TIP \u2013 ICT & KPK",
  theme: ["Education"],
  subtheme: ["Foundational Literacy & Numeracy"],
  description: "Designed and ran an RCT testing a scripted, levelled-grouping remedial program in Urdu, Math, and English. COVID-19 widened foundational learning gaps, particularly for lower socio-economic students. The trial demonstrated significant learning gains, generating the evidence base for subsequent Balochistan and national-scale rollouts.",
  partners: "Marshal Foundation, RISE (FCDO), World Bank, JICA",
  status: "Completed",
  serviceLine: ["Program Design & Implementation Support", "Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "confirmed"
},
{
  id: "edu-niete",
  name: "National Institute of Excellence in Teacher Education (NIETE)",
  theme: ["Education"],
  subtheme: ["Teacher Development"],
  description: "Supports embedded monitoring and process evaluation of a technology-enabled teacher training program across all 341 FDE schools in ICT. Pakistan faces a persistent shortage of high-quality teacher training. Evaluation findings on teacher competency gains expected at close of the two-year intervention in 2026.",
  partners: "Ministry of Federal Education & Professional Training, Taleemabad",
  status: "Ongoing",
  serviceLine: ["Program Design & Implementation Support", "Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["Quasi-Experimental"],
  confidence: "confirmed"
},
{
  id: "edu-teachers-expectations",
  name: "Teacher's Expectations Project",
  theme: ["Education"],
  subtheme: ["Teacher Development"],
  description: "Designed an RCT with three delivery arms \u2014 individual, paired, and parent-directed \u2014 testing whether teacher expectations affect student cognitive and non-cognitive outcomes. Pandemic-era remote learning reduced student motivation, and prior research indicated teacher expectations influence effort. The RCT measured impacts on student outcomes and parental engagement.",
  partners: "J-PAL, RISE, Beaconhouse School System",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "confirmed"
},
{
  id: "edu-ilm-exchange",
  name: "Ilm Exchange",
  theme: ["Education"],
  subtheme: ["EdTech"],
  description: "Built and tested a digital marketplace connecting schools, teachers, and students to affordable educational goods and financial services. Fragmented access to quality resources limited schools' ability to improve learning outcomes. The platform is testing whether sufficient demand and supply exist to sustain a national education marketplace hub.",
  partners: "Malala Fund, J-PAL, Ilm Ideas 2",
  status: "Ongoing",
  serviceLine: ["Decision Support Systems"],
  tier2: [],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "edu-taleemabad-validation",
  name: "Taleemabad Evaluation Validation Exercise",
  theme: ["Education"],
  subtheme: ["EdTech"],
  description: "Conducted an independent third-party audit benchmarking Taleemabad's internal assessment data against standardised external tools. Taleemabad's EdTech platform required external validation to credibly demonstrate learning impact at pre-primary and primary levels. The audit independently confirmed whether the platform improved student learning outcomes.",
  partners: "Taleemabad",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "edu-rise",
  name: "Research on Improving Systems of Education (RISE)",
  theme: ["Education"],
  subtheme: ["Education Systems & Policy"],
  description: "Applied economic market analysis tools across Punjab, KP, and ICT to study the full schooling environment. Over 40% of Pakistan's primary-age students attend low-cost private schools, creating a distinctive marketplace for studying systemic constraints. The research produced a systems-level account of binding constraints limiting all education actors.",
  partners: "FCDO, BSS, MicroFinance Banks, LUMS SOE, IDEAS",
  status: "Completed",
  serviceLine: ["Decision Support Systems"],
  tier2: [],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "edu-leaps",
  name: "Learning and Educational Achievements in Pakistan Schools (LEAPS)",
  theme: ["Education"],
  subtheme: ["Education Systems & Policy"],
  description: "Ran a large-scale longitudinal study testing over 22,000 children in grades 3\u20135, examining how financial product access affects school performance. Despite rising enrolment, learning deficits in Urdu, English, and Mathematics persisted. The study established resource constraints as a binding factor on performance across public and private providers.",
  partners: "World Bank, Ministry of Education",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["Longitudinal Study"],
  confidence: "confirmed"
},
{
  id: "edu-kpk-census",
  name: "Khyber Pakhtunkhwa School Census",
  theme: ["Education"],
  subtheme: ["Education Systems & Policy"],
  description: "Administered Survey CTO-based instruments across 10 districts via in-person surveys and CATI back-checks to capture private school characteristics. Limited reliable data on private schools constrained education planning across KPK. Despite COVID-19 disruption, approximately 6,000 surveys were completed across 6 districts, capturing geo-location, fees, salaries, and enrolment data.",
  partners: "DFID (FCDO)",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census"],
  confidence: "confirmed"
},
{
  id: "edu-oosc-feasibility",
  name: "Feasibility Study: Out-of-School Children & Outcome-Based Financing",
  theme: ["Education", "Economic Opportunity"],
  subtheme: ["Education Financing"],
  description: "Conducted a nationwide scoping and market analysis of non-formal education and low-cost private school sectors. Pakistan has 20.3 million out-of-school children, and 75% cannot read age-appropriate text by age 10. The study produced per-child delivery cost estimates and recommended an outcome-based financing model to improve enrolment.",
  partners: "World Bank, British Asian Trust, Haidermota & Co.",
  status: "Ongoing",
  serviceLine: ["Decision Support Systems"],
  tier2: [],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "edu-financing-support",
  name: "Education Financing and Support Services Project",
  theme: ["Education", "Economic Opportunity"],
  subtheme: ["Education Financing", "Microfinance/Lending"],
  description: "Designed, implemented, and evaluated a financial and support services model for private school entrepreneurs in Punjab. Pakistan's private education sector lacked sustainable access to finance and quality support services. The evaluation assessed the impact of different financial products on loan uptake, school performance, and service quality adoption.",
  partners: "World Bank, Oxford University Press, Tameer Microfinance Bank, Aman Foundation",
  status: "Completed",
  serviceLine: ["Program Design & Implementation Support", "Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "edu-parent-engagement",
  name: "Parent Engagement Project",
  theme: ["Education"],
  subtheme: ["Parent & Community Engagement"],
  description: "Ran a pilot study in five districts testing whether citizen engagement platforms increased political knowledge, trust in government, and learning outcomes. Citizens had limited structured platforms for raising school quality concerns with government actors. Ongoing \u2014 outcomes on the political economy of parent involvement expected at study close.",
  partners: "J-PAL, National Rural Support Programme, Idara-e-Taleem-o-Agahi",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "edu-tech-empower",
  name: "Technology to Empower Actors Across the Learning Ecosystem",
  theme: ["Education"],
  subtheme: ["Parent & Community Engagement", "EdTech"],
  description: "Running an RCT testing whether technology-aided information and guidance interventions \u2014 delivered to school-based and home-based actors independently or jointly \u2014 improve learning outcomes. Pandemic school closures exposed coordination and information gaps. Ongoing \u2014 outcomes on the most cost-effective configuration of support expected at close of intervention.",
  partners: "EdTech Hub (R4D/FCDO), RISE (FCDO), World Bank, MoFEPT",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "confirmed"
},
{
  id: "edu-learning-beyond-school",
  name: "Learning Beyond School: Out-of-School Adolescent Girls in Pakistan",
  theme: ["Education", "Gender & Inclusion"],
  subtheme: [],
  description: "Conducting an RCT across 300 villages in southern Punjab testing a remedial literacy program for out-of-school females aged 9\u201319. Despite enrolment gains, 59% of girls do not complete primary school. Ongoing \u2014 outcomes on learning, enrolment, empowerment, and household attitudes expected at close of intervention.",
  partners: "MIT, J-PAL (PPE)",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "confirmed"
},
{
  id: "edu-market-tutors",
  name: "Market for Tutors",
  theme: ["Education", "Gender & Inclusion", "Economic Opportunity"],
  subtheme: ["Labor Markets"],
  description: "Mapped local private tutoring markets through household surveys, tutor interviews, and network analysis across 21 markets covering 15,000+ households in Rahim Yar Khan, Attock, and Faisalabad. Private tutoring is widespread yet little evidence exists on how these markets function. Findings will inform interventions expanding quality tutoring access and female employment.",
  partners: "J-PAL",
  status: "Ongoing",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census", "Qualitative"],
  confidence: "confirmed"
},
{
  id: "edu-happiness",
  name: "Evaluation of The Happiness Project",
  theme: ["Education"],
  subtheme: [],
  description: "Evaluated a five-module social-emotional learning program for Grade 3\u20138 students using a pre-post assessment design across schools in Lahore and Sheikhupura. Standard curricula lack structured emotional development support. The evaluation assessed improvements in students' emotional understanding, confidence, and collaborative behaviour.",
  partners: "Care Foundation",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "health-sopran",
  name: "MLE for Leveraging Pakistan's Social Protection Program for Adolescent Girls' Nutrition (SOPRAN)",
  theme: ["Health", "Education", "Gender & Inclusion"],
  subtheme: ["Nutrition"],
  description: "Integrated adolescent nutrition into BISP Taleemi Wazaif (Conditional Cash Transfer Programme) with school-based education, IFA supplementation, and access to fortified flour to improve girls' nutrition, using MLE to assess impact and guide scale-up while positioning girls as community change-makers.",
  partners: "Gates Foundation, GIZ",
  status: "Ongoing",
  serviceLine: ["Program Design & Implementation Support", "Evaluations"],
  tier2: ["MLE"],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "health-scale",
  name: "Smart Containment with Active Learning (SCALE)",
  theme: ["Health", "Governance"],
  subtheme: [],
  description: "SCALE brought together Pakistani and international experts across public health, policy, economics, data analytics, and technology to support Pakistan's COVID-19 response through survey design, data collection, and analysis, directly informing evidence-based policymaking and the country's SMART lockdown strategy.",
  partners: "FCDO, Punjab Primary & Secondary Healthcare Department",
  status: "Completed",
  serviceLine: ["Decision Support Systems"],
  tier2: [],
  tier3: [],
  confidence: "review"
},
{
  id: "health-screening-camps",
  name: "Analysis of Health Week Screening Camps",
  theme: ["Health"],
  subtheme: [],
  description: "Analyzed data from 927,000+ individuals screened during Integrated Health Week camps in 2023, covering blood-borne communicable diseases and NCDs, to estimate disease prevalence, assess socioeconomic determinants, and generate evidence for prevention strategies, regional interventions, and targeted resource allocation.",
  partners: "CLEAR PCA, Primary & Secondary Healthcare Department",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Analytical Foundation"],
  tier3: ["Descriptive Statistics"],
  confidence: "review"
},
{
  id: "health-private-study",
  name: "Private Healthcare Study",
  theme: ["Health"],
  subtheme: [],
  description: "Profiled 289 private hospitals across 16 Pakistani cities and surveyed 1,143 healthcare consumers to assess accessibility, service quality, pricing, market failures, supply-side gaps, and tele-health/tech-enabled delivery models, generating evidence to identify capital-driven investment opportunities for Karandaaz in private healthcare delivery.",
  partners: "Karandaaz",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census"],
  confidence: "review"
},
{
  id: "health-dmpa-sc",
  name: "MLE of DMPA-SC Roll-out through Private Sector",
  theme: ["Health"],
  subtheme: ["Health Financing"],
  description: "MLE partner for the evidence-based introduction of DMPA-SC, a self-injectable contraceptive, into Pakistan's private pharmacy market, conducting formative research, pricing studies, demand generation testing, and multi-level progress tracking to measure outcomes and inform global scale-up of effective commercialization approaches.",
  partners: "Gates Foundation, Mathematica Inc., Remington",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["MLE"],
  tier3: [],
  confidence: "review"
},
{
  id: "health-adaptive-social-protection",
  name: "MLE of Adaptive Social Protection",
  theme: ["Health", "Social Protection", "Gender & Inclusion"],
  subtheme: [],
  description: "Designed and evaluated 3 Adaptive Social Protection pilots in Sindh using a quasi-experimental Differences-in-Differences design to assess impacts on women's economic resilience, female agricultural workers' livelihoods, maternal health-linked savings, and urban informal workers' access to formal recognition, financial services, and social protection.",
  partners: "GIZ",
  status: "Completed",
  serviceLine: ["Evaluations", "Advanced Analytics"],
  tier2: ["MLE", "Econometric Modeling"],
  tier3: ["Quasi-Experimental"],
  confidence: "confirmed"
},
{
  id: "health-bigcatchup",
  name: "Case Studies of Big Catch-up Activities in LMICs",
  theme: ["Health"],
  subtheme: ["Immunization & Vaccines"],
  description: "Evaluated Pakistan's post-COVID immunization recovery efforts in Punjab and Sindh using mixed methods, including desk reviews, KIIs, FGDs, and caregiver/vaccinator surveys, to identify barriers, implementation gaps, and strategies for restoring routine vaccination among zero-dose and under-immunized children.",
  partners: "GAVI, Rayn Consulting, WHO",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Process Evaluation"],
  tier3: ["Mixed Methods"],
  confidence: "review"
},
{
  id: "health-camps-kp-balochistan",
  name: "Assessment of Health Camps in KP and Balochistan",
  theme: ["Health"],
  subtheme: ["Immunization & Vaccines"],
  description: "Assessed 30+ health camps delivering routine immunization, polio vaccination, and essential health services in underserved and security-compromised areas, using field observations and stakeholder interviews to evaluate service delivery quality, community mobilization, and vaccine uptake.",
  partners: "Gates Foundation",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Process Evaluation"],
  tier3: ["Qualitative"],
  confidence: "review"
},
{
  id: "health-hepatitis",
  name: "Hepatitis Control Program (Health Data System Practices and Budget Impact Analysis)",
  theme: ["Health", "Governance"],
  subtheme: [],
  description: "Evaluated Punjab's hepatitis data systems using the PRISM framework and conducted activity-based costing to strengthen routine health information systems, support evidence-based financing, and advance progress toward hepatitis elimination by 2030.",
  partners: "CLEAR PCA, Primary & Secondary Healthcare Department",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: [],
  confidence: "review"
},
{
  id: "health-anc-mamta",
  name: "Increasing Uptake of ANC Services by Mamta Beneficiaries",
  theme: ["Health", "Gender & Inclusion"],
  subtheme: ["Maternal & Child Health"],
  description: "Deployed AI-powered ultrasound machines at Mamta Centres in rural Sindh to increase early program enrolment among underserved women in Sindh's lowest wealth quintiles, while evaluating their impact on ANC uptake and high-risk pregnancy referrals using a stepped-wedge randomized design.",
  partners: "PPHI, Gates Foundation",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["Stepped Wedge"],
  confidence: "review"
},
{
  id: "health-mcw-products",
  name: "Increasing Access to MCW Products",
  theme: ["Health"],
  subtheme: ["Maternal & Child Health", "Nutrition"],
  description: "Used a hypothesis-driven market analysis to identify barriers and enablers to introducing and scaling maternal and child nutrition products in Pakistan, including RUTF, SQ-LNS, LNS-PLW/BEP, and alternative RUTF formulations, by examining financing, demand, supply, and delivery systems to inform future intervention strategies.",
  partners: "Gates Foundation, R4D",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Analytical Foundation"],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "health-mnch-healthtech",
  name: "Improving MNCH Outcomes: HealthTech Solutions with a Purpose",
  theme: ["Health"],
  subtheme: ["HealthTech", "Maternal & Child Health"],
  description: "Developed an mHealth app to train CHWs and standardize culturally appropriate breastfeeding support aligned with WHO guidelines, improving postpartum care in Punjab and scalable across LMICs.",
  partners: "USAID",
  status: "Completed",
  serviceLine: ["Digital Transformations"],
  tier2: [],
  tier3: [],
  confidence: "review"
},
{
  id: "health-micare",
  name: "Creating Indigenous Digital Tools: Women-Led Digital Solutions (MiCare)",
  theme: ["Health", "Gender & Inclusion"],
  subtheme: ["HealthTech", "Maternal & Child Health"],
  description: "Designed and deployed a low-bandwidth mobile health platform (MiCare) for CHWs to digitize monitoring, training, and decision support for WHO-aligned breastfeeding practices, enabling scalable data-driven MLE and improved infant nutrition outcomes in rural communities.",
  partners: "Gates Foundation, RSPN, Mathematica Inc.",
  status: "Completed",
  serviceLine: ["Digital Transformations", "Program Design & Implementation Support"],
  tier2: [],
  tier3: [],
  confidence: "confirmed"
},
{
  id: "health-sehatdost",
  name: "Sehatdost",
  theme: ["Health"],
  subtheme: ["HealthTech"],
  description: "Developed a digital platform providing stigma-free access to HIV/AIDS information, peer discussion, and guidance on prevention and treatment to address barriers in sensitive-topic research and healthcare engagement, reaching 20,000+ users and enabling scalable integration with public health systems.",
  partners: "(missing)",
  status: "Completed",
  serviceLine: [],
  tier2: [],
  tier3: [],
  confidence: "untagged"
},
{
  id: "health-femtech",
  name: "Femtech Innovation Hub for Pakistan",
  theme: ["Health", "Gender & Inclusion", "Economic Opportunity"],
  subtheme: ["HealthTech"],
  description: "Established a Women's Health Innovation Hub to identify and support FemTech startups developing cost-effective health solutions for low-income women, enabling scalable innovation in women's physical and mental health.",
  partners: "Gates Foundation, LUMS",
  status: "Ongoing",
  serviceLine: [],
  tier2: [],
  tier3: [],
  confidence: "schema-flag"
},
{
  id: "health-bep-market-test",
  name: "Market Test of Balanced Energy Protein Supplement in Pakistan",
  theme: ["Health"],
  subtheme: ["Nutrition"],
  description: "Strengthened community-based delivery of maternal nutrition products by testing door-to-door BEP distribution models, supporting frontline workers with improved monitoring tools, and identifying workforce challenges linked to digital literacy and manual data collection.",
  partners: "Gates Foundation",
  status: "Completed",
  serviceLine: ["Program Design & Implementation Support", "Decision Support Systems"],
  tier2: [],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-asset-transfer",
  name: "Asset Transfer Project",
  theme: ["Social Protection"],
  subtheme: ["Poverty"],
  description: "Used an RCT in Southern Punjab to compare asset transfers with cash transfers among ultra-poor households, measuring effects on income, productivity, consumption, and asset ownership to inform the design of more effective social safety-net programs.",
  partners: "IGC, Pakistan Poverty Alleviation Fund, National Rural Support Program, Farmer Development Organization",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "misc-food-insecurity-survey",
  name: "World Bank Food Insecurity Survey",
  theme: ["Social Protection"],
  subtheme: ["Poverty"],
  description: "Conducted CATI surveys and built real-time dashboards during COVID-19 to map income loss, food insecurity, hunger, ration access, and price pressures in Karachi's informal settlements for targeted government relief allocation.",
  partners: "World Bank, Karachi city government",
  status: "Completed",
  serviceLine: ["Advanced Analytics", "Decision Support Systems"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census"],
  confidence: "review"
},
{
  id: "misc-ecd-ultrapoor",
  name: "Impact of Social Assistance on Early Childhood Development among Ultra-Poor Households",
  theme: ["Social Protection", "Health"],
  subtheme: ["Poverty", "Maternal & Child Health"],
  description: "Builts on the Asset Transfer RCT to study how cash and asset transfers affected children's cognitive, non-cognitive, and health outcomes, using validated child-development tools, caregiver surveys, and household data in South Punjab.",
  partners: "3IE, Yale University",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "misc-climate-adaptation",
  name: "Barriers to Climate Adaptation",
  theme: ["Climate & Environment", "Social Protection"],
  subtheme: ["Poverty"],
  description: "Tracks 5,000 ultra-poor rural households over time to study how flood exposure affects migration, employment, assets, and welfare, while identifying the barriers that limit climate adaptation and occupational mobility among vulnerable communities.",
  partners: "IGC, CEPR-STEG, RSPN, Urban Unit",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["Longitudinal Study"],
  confidence: "review"
},
{
  id: "misc-zinc-wheat",
  name: "Harnessing Digital Extension to Promote Zinc-Biofortified Wheat Seeds",
  theme: ["Climate & Environment"],
  subtheme: ["Agriculture"],
  description: "Promoted zinc-biofortified wheat seeds in Punjab through SMS, robocalls, helpline support, and farmer surveys to address malnutrition, increase awareness and adoption, and assess farmer-reported changes in usefulness, yield, and income.",
  partners: "HarvestPlus, Precision Development/PxD, CGIAR",
  status: "Completed",
  serviceLine: ["Program Design & Implementation Support", "Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-pxd-weather",
  name: "PxD Weather-Based Forecast Activity",
  theme: ["Climate & Environment"],
  subtheme: ["Agriculture"],
  description: "Developed weather-aware agricultural advisories using granular forecasts and farmer feedback to test how standalone and integrated weather messages can support climate adaptation, improve input timing, reduce costs, and increase smallholder productivity.",
  partners: "IFAD, CFAN, Agriculture Department Government of Punjab, CERP",
  status: "Completed",
  serviceLine: ["Program Design & Implementation Support", "Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-air-pollution",
  name: "World Bank Project: Technical Assistance to Measure Air Pollution",
  theme: ["Climate & Environment"],
  subtheme: ["Air Quality/Pollution"],
  description: "Deployed 75 air-quality sensors across Lahore using an experimental placement design to measure hyperlocal pollution variation, assess socio-economic exposure differences, and support Pakistan's Country Climate and Development Report.",
  partners: "World Bank",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Econometric Modeling"],
  tier3: ["Experimental Design"],
  confidence: "review"
},
{
  id: "misc-crop-burning",
  name: "Crop Burning in Punjab",
  theme: ["Climate & Environment"],
  subtheme: ["Agriculture", "Air Quality/Pollution"],
  description: "Evaluates Punjab's subsidized rice-residue management machinery program using administrative data, satellite imagery, spot-checks, farmer surveys, and focus groups to assess effects on stubble burning, air pollution, yields, profits, and soil quality.",
  partners: "ATAI-JPAL, University of Chicago, IGC, Precision Development, CERP, Government of Punjab",
  status: "Ongoing",
  serviceLine: ["Evaluations", "Advanced Analytics"],
  tier2: ["Impact Evaluation", "Applied Methods"],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-agri-lending",
  name: "Lending in Agriculture Project",
  theme: ["Climate & Environment", "Economic Opportunity"],
  subtheme: ["Agriculture", "Microfinance/Lending"],
  description: "Studies HBL's integrated agricultural finance model for smallholders through credit, input access, advisory support, market linkages, farmer surveys, plot-level data, and satellite monitoring to improve productivity, profitability, and financial inclusion.",
  partners: "Habib Bank Limited, Princeton University, Yale University",
  status: "Ongoing",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-gender-transport",
  name: "Gender Norms and Transport Project",
  theme: ["Gender & Inclusion"],
  subtheme: [],
  description: "Tests whether motorbike training and financing can reduce women's mobility constraints in Karachi, where unsafe transport limits employment and education, by measuring effects on mobility, agency, and labor-force participation.",
  partners: "IGC Pakistan, J-PAL, The Hunar Foundation, Pink Riders Pakistan, Kashf Foundation",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-womens-mobility",
  name: "Women's Mobility Program",
  theme: ["Gender & Inclusion", "Economic Opportunity"],
  subtheme: ["Labor Markets"],
  description: "Uses the Job Talash platform and randomized interventions, including safe transport, search encouragement, and jobseeker auditing, to study labor-market frictions in Lahore and improve women's job applications, interviews, mobility, and employment outcomes.",
  partners: "DFID-IZA, NSF, J-PAL, IGC, ADB, DIV USAID, PEDL, IPA, Punjab Social Welfare Department",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "misc-social-norms",
  name: "Social Norms Project",
  theme: ["Gender & Inclusion"],
  subtheme: [],
  description: "Used a cluster RCT across rural Sindh and Punjab to test whether mobile cinema, discussions, and gender workshops could shift norms around child marriage and girls' education, reducing child marriage through gender-targeted pathways.",
  partners: "Oxford University, Indus Resource Centre, Bedari, Oxfam Novib, Oxfam Pakistan, Amsterdam Institute for Global Health and Development",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "misc-social-compact",
  name: "Social Compact: Urban Services and Taxes",
  theme: ["Governance"],
  subtheme: ["Taxation"],
  description: "Examines reforms that link local property tax collection with visible urban service delivery in Punjab, using citizen preference mechanisms to strengthen accountability, improve trust, and encourage greater tax compliance.",
  partners: "Excise, Taxation and Narcotics Control Department Punjab, Red Buffer Pakistan, Sub-National Governance Programme's Innovation Challenge Fund",
  status: "Completed",
  serviceLine: ["Decision Support Systems"],
  tier2: [],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-property-tax",
  name: "Property Tax Innovation through Digital Technology",
  theme: ["Governance"],
  subtheme: ["Taxation"],
  description: "Designs an AI- and machine-learning-enabled property tax system for Punjab to identify unassessed properties, reduce underassessment, improve tax collector performance, enhance taxpayer services, and measure adoption of digital reforms.",
  partners: "Excise, Taxation and Narcotics Control Department Punjab, Red Buffer Pakistan, Sub-National Governance Programme's Innovation Challenge Fund",
  status: "Completed",
  serviceLine: ["Digital Transformations"],
  tier2: [],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-training-quality",
  name: "Training Quality Assessment of Circle's Digital Literacy Program",
  theme: ["Economic Opportunity"],
  subtheme: ["Skills"],
  description: "Assessed Circle's Digital Literacy Program in Punjab by reviewing learning-outcome measurement, quiz design, data quality, training delivery, stakeholder feedback, and dropout factors to improve program effectiveness and evidence-based decision-making.",
  partners: "Circle Women Association, Bill & Melinda Gates Foundation",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Process Evaluation"],
  tier3: [],
  confidence: "review"
},
{
  id: "misc-punjab-economic-opportunities",
  name: "Punjab Economic Opportunities Program",
  theme: ["Economic Opportunity", "Gender & Inclusion"],
  subtheme: ["Skills", "Labor Markets"],
  description: "Evaluates vocational training, stipend, voucher, and market-linkage schemes in Southern Punjab to identify barriers to skills uptake, especially among women, and measure effects on income, employment, empowerment, and cost-effectiveness.",
  partners: "Government of Punjab, Punjab Skills Development Fund, DFID/FCDO, British Asian Trust, Kaarvan Crafts Foundation, J-PAL",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "review"
},
{
  id: "fin-gsma-women-microentrepreneurs",
  name: "GSMA-Empowering Women Micro-Entrepreneurs",
  theme: ["Economic Opportunity", "Gender & Inclusion"],
  subtheme: ["Microfinance/Lending"],
  description: "Conducted a qualitative study using the Sociology of Knowledge Approach to Discourse (SKAD) framework to evaluate JazzCash's digital financial services (DFS) onboarding model for women micro-entrepreneurs (WMEs) in Karachi, Lahore, and Islamabad. Persistent gender gaps in DFS uptake limit women-led businesses to cash-dependent, informal operation. The study identified adoption enablers (peer visibility, female-led onboarding) and barriers (gatekeeper resistance, scam fears), informing JazzCash's onboarding design and customer education strategy.",
  partners: "GSMA, JazzCash",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: ["Qualitative"],
  confidence: "review"
},
{
  id: "health-ppif-behavioral-fp",
  name: "Behavioral and Attitudinal Studies and Impact Assessment Surveys (PPIF)",
  theme: ["Health"],
  subtheme: [],
  description: "Designing a mixed-methods impact evaluation of a government-produced television drama serial embedding family planning messages, using baseline/midline/endline surveys, FGDs, KIIs, and secondary data triangulation across 10 districts of Punjab. Modern family planning uptake remains low in Pakistan despite information campaigns. As of this session, work is limited to survey instrument design and sample power calculations due to contracting delays; the causal impact analysis has not yet begun.",
  partners: "Punjab Population Innovation Fund (PPIF), CERP Learning Hub",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "review"
},
{
  id: "econ-industrial-upgrading",
  name: "Barriers to Industrial Upgrading Project",
  theme: ["Economic Opportunity"],
  subtheme: [],
  description: "Ran a randomized input-subsidy experiment and a matching-grant pilot to study barriers to innovation and quality upgrading in Sialkot's football and surgical-goods manufacturing sectors, alongside long-term high-frequency censuses of both industries. Pakistani manufacturers face declining competitiveness as upgrading stalls amid rising automation and import competition. The football-sector subsidy and surgical-sector matching-grant pilot generated evidence on technology adoption and firm-level innovation responses, published across multiple peer-reviewed outlets.",
  partners: "Private Enterprise Development in Low-Income Countries (PEDL)",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "gov-political-linkages",
  name: "Political Linkages Project",
  theme: ["Governance"],
  subtheme: [],
  description: "Ran a pilot field experiment testing whether Interactive Voice Response (IVR) technology connecting legislators and rural voters in Peshawar improved electoral accountability and voters' sense of efficacy. Politicians lack low-cost channels to collect constituent feedback between elections. Baseline/endline surveys around an IVR-mediated service-delivery feedback loop measured shifts in trust, perceived responsiveness, and support for democracy.",
  partners: "J-PAL, IGC, SANGUM, CERP, Provincial Assembly of KP",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "gov-state-authority",
  name: "State Authority Project",
  theme: ["Governance"],
  subtheme: [],
  description: "Ran a two-phase randomized controlled trial in Lahore testing whether providing citizens with positive information about improving state dispute-resolution services shifts trust and engagement away from non-state actors. Declining allegiance to state institutions across Pakistan raises concerns about weakening governance. Phase 1 found that truthful positive information about reduced court delays increased citizens' willingness to use state courts and reduced engagement with non-state alternatives; Phase 2 extended this to citizens actively experiencing disputes via Punjab's emergency helpline.",
  partners: "JPAL, Punjab Police, Punjab Safe Cities Authority, Legal Aid Society",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "edu-targeted-instruction",
  name: "Targeted Instruction Program",
  theme: ["Education"],
  subtheme: ["Foundational Literacy & Numeracy"],
  description: "Evaluated a technology-supported, teacher-led foundational learning recovery program across 1,250 public primary schools in Peshawar and Mardan, targeting 250,000 students using a randomized control-school design. COVID-19 school closures worsened pre-existing foundational learning gaps in Urdu, Math, and English, especially among lower socioeconomic students. Initial pilot cycles showed test-score gains of roughly 0.5 standard deviations, with score-card interventions also increasing test scores by 42%, reducing private-school fees by 17%, and raising primary enrollment by 4.5%.",
  partners: "Marshall Foundation, RISE (FCDO), World Bank (SIEF, RRREP, PREP), JICA",
  status: "Completed",
  serviceLine: ["Program Design & Implementation Support", "Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "gov-computer-vision-tax",
  name: "Computer Vision Project",
  theme: ["Governance"],
  subtheme: ["Taxation"],
  description: "Developing and field-testing a computer vision algorithm that predicts property features and valuations from property images to improve Urban Immovable Property Tax (UIPT) collection in Punjab, building on a multi-year administrative-image database achieving over 80% feature-prediction accuracy. Outdated property valuations are a key constraint on tax revenue, with only 2 of 5.1 million properties currently taxable. A randomized controlled trial design will compare the algorithm's performance against status-quo tax-inspector discretion across property reassessment, taxpayer-facing transparency messaging, and inspector audit accuracy.",
  partners: "J-PAL, MIT, Excise Taxation and Narcotics Control Department, Urban Unit",
  status: "Completed",
  serviceLine: ["Advanced Analytics", "Evaluations"],
  tier2: ["Applied Methods", "Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "health-demand-maternal-supplements",
  name: "Demand for Maternal Nutritional Supplements Study",
  theme: ["Health", "Gender & Inclusion"],
  subtheme: ["Nutrition"],
  description: "Surveyed 159 urban and 201 rural pregnant and lactating women plus community resource persons and healthcare providers in Karachi and Jacobabad to compare consumer demand, switching behavior, and supply-chain dynamics for two maternal nutrition products (Wellma/BEP and MiCare/MMS). The study supported product optimization and market planning ahead of further scale-up. Findings showed a rural preference for Wellma's paste format and an urban preference for MiCare's tablet convenience, with affordability and provider trust as key drivers of adoption and switching.",
  partners: "Gates Foundation, Mathematica",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census"],
  confidence: "review"
},
{
  id: "econ-retail-sme-segmentation",
  name: "Retail SME Market Segmentation Study",
  theme: ["Economic Opportunity"],
  subtheme: [],
  description: "Designed a customer-centered SME financial-services strategy for a new Shariah-compliant digital bank, combining market-sizing analysis, a 1,000-retailer survey across five cities, behavioral persona clustering, and FGD-based product validation. Pakistan's 3.3 million SME retailers remain largely excluded from formal financial services due to informality and trust gaps. The engagement delivered eight validated SME personas, a phased go-to-market strategy, a competitive benchmarking report, and an M&E framework for post-launch product tracking.",
  partners: "Raqami Islamic Digital Bank",
  status: "Completed",
  serviceLine: ["Advanced Analytics", "Decision Support Systems"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census", "Qualitative"],
  confidence: "review"
},
{
  id: "health-r4d-mcw-commodities",
  name: "R4D - Increasing Access to Maternal and Child Wasting Nutrition Commodities",
  theme: ["Health"],
  subtheme: ["Nutrition"],
  description: "Conducted a landscaping study of regulatory, financing, demand, and supply dynamics for four lipid-based maternal and child wasting-treatment commodities (RUTF, RUSF, LNS-MQ, LNS-PLW) in Khyber Pakhtunkhwa. Wasting-treatment products remain neglected within Pakistan's broader nutrition agenda, relying on fragmented, donor-driven support rather than sustained government investment. The study found donor dependence, sub-10% coverage, and regulatory gaps (key products excluded from WHO's and Pakistan's Essential Medicines Lists), and recommended integrating procurement into routine health systems and clarifying DRAP's regulatory mandate.",
  partners: "Gates Foundation, Results for Development (R4D)",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Analytical Foundation"],
  tier3: [],
  confidence: "review"
},
{
  id: "health-micare-bep-business-model",
  name: "MiCare: Impact of Technology Intervention on the Balanced Energy Protein Business Model",
  theme: ["Health", "Gender & Inclusion"],
  subtheme: ["Nutrition", "HealthTech"],
  description: "Designed, piloted, and evaluated a digital data-collection and sales-tracking platform (MiCare) replacing paper-based systems for community resource persons distributing Balanced Energy Protein supplements door-to-door in Sindh and Punjab. Manual data systems caused month-long lags in actionable insight, limiting targeted outreach to undernourished pregnant and lactating women. The platform eliminated the data lag entirely, expanded monthly outreach to over 15,000 women, and produced measurable gains in CRPs' digital literacy, mobility, and social status.",
  partners: "Gates Foundation, Mathematica",
  status: "Completed",
  serviceLine: ["Digital Transformations", "Program Design & Implementation Support"],
  tier2: [],
  tier3: [],
  confidence: "review"
},
{
  id: "econ-better-cotton-kap",
  name: "Better Cotton: Comprehensive KAP Assessment Study & Data Collection",
  theme: ["Climate & Environment", "Economic Opportunity"],
  subtheme: ["Agriculture"],
  description: "Conducted a mixed-methods Knowledge, Attitudes, and Practices (KAP) assessment of a sustainable-cotton-farming capacity-building program in Rajanpur District, combining 424 farmer surveys with FGDs and KIIs across program stakeholders. The program supports over 32,000 cotton farmers but lacked an evidence base on adoption barriers and motivational drivers behind sustainable-practice uptake. Findings informed recommendations on training design, farmer-segment-specific engagement strategies, and communication tools to improve adoption, particularly among smallholders and female farmers.",
  partners: "Better Cotton",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Process Evaluation"],
  tier3: ["Mixed Methods"],
  confidence: "review"
},
{
  id: "health-admin-data-punjab-health",
  name: "Analysis of Administrative Data to Enhance M&E Practices in Punjab Health Department",
  theme: ["Health", "Governance"],
  subtheme: [],
  description: "Analyzed administrative data from 2023 Integrated Health Week and Special Needs Children screening camps, layered with national survey and census data, to strengthen the Primary & Secondary Healthcare Department's monitoring and evaluation capacity. Pakistan carries a high burden of Hepatitis B/C and non-communicable disease, with limited systematic use of administrative health data for program insight. The analysis revealed distinct demographic and geographic disease patterns across Punjab and produced immediate, medium-, and long-term recommendations to strengthen the department's M&E system and in-house analytic capacity.",
  partners: "CLEAR PCA, CERP, Primary and Secondary Healthcare Department (P&SHD)",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Analytical Foundation"],
  tier3: ["Descriptive Statistics"],
  confidence: "review"
},
{
  id: "health-prism-his-evaluation",
  name: "PRISM Evaluation of Punjab's Health Information Systems",
  theme: ["Health", "Governance"],
  subtheme: [],
  description: "Conducted a diagnostic evaluation of Punjab's health information systems using the PRISM (Performance of Routine Information System Management) framework, focused on the Hepatitis Control Program as a representative case, through key informant interviews and clinic visits across Punjab's three zones. Despite significant digitization investment, fragmented reporting, poor system interoperability, and underused dashboards limit evidence-based decision-making. The evaluation identified EMR inconsistencies and SOP gaps, informed redesign discussions feeding into the Prime Minister's Hepatitis Elimination Program, and set a replicable model for evaluating vertical health programs.",
  partners: "CLEAR PCA, Primary and Secondary Healthcare Department, Hepatitis Control Program, Health Information & Service Delivery Unit",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: [],
  confidence: "review"
},
{
  id: "gov-clear-pca-planning-commission",
  name: "Clear PCA Planning Commission",
  theme: ["Governance"],
  subtheme: [],
  description: "Conducted a needs-based assessment and Human-Centered Design workshop to strengthen the Monitoring and Evaluation function of Pakistan's Planning Commission, which oversees third-party M&E for over 900 Public Sector Development Programme projects. Inconsistent M&E inclusion in project design and the absence of a department-wide MIS plan weakened the Commission's ability to generate and use data effectively. The engagement produced actionable recommendations on PC-1 documentation standards, M&E budget provisions, and a technical assessment of the Commission's web-based Projects Monitoring and Evaluation System (PMES).",
  partners: "CLEAR PCA, Global Evaluation Initiative, Planning Commission of Pakistan",
  status: "Completed",
  serviceLine: ["Decision Support Systems"],
  tier2: [],
  tier3: [],
  confidence: "review"
},
{
  id: "gov-willingness-to-pay-survey",
  name: "Willingness to Pay Survey",
  theme: ["Governance"],
  subtheme: [],
  description: "Conducted a stratified survey of roughly 2,500 households across seven Punjab cities to assess willingness and capacity to pay for water supply, sewerage, and solid waste management services, supporting an Asian Development Bank Project Readiness Financing facility. The study informed how improved municipal services could affect affordability, equity, and service access in intermediate cities. Findings showed general willingness to pay more for improved service quality, particularly among industrial property owners, with sewerage and waste management satisfaction outpacing water supply.",
  partners: "OSMANI, Asian Development Bank",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census"],
  confidence: "review"
},
{
  id: "econ-punjab-human-capital-market-assessment",
  name: "Market Assessment for Punjab Human Capital Investment Project Economic Inclusion Component (World Bank)",
  theme: ["Economic Opportunity", "Social Protection"],
  subtheme: ["Labor Markets", "Poverty"],
  description: "Conducted an economic mapping and value-chain analysis of on- and off-farm livelihood opportunities in Bahawalpur and Muzaffargarh through a 450-household survey, private-sector stakeholder interviews, and Human-Centered Design workshops, to identify economic-inclusion interventions for poor households. Pakistan's human development indicators lag the South Asia regional average, with the World Bank-backed BISP system seeking complementary livelihood pathways for beneficiaries. The study identified viable livelihood options including mechanized farming, cottage industries, and digital freelancing, while finding that interventions must be tailored to local socioeconomic context and foundational literacy levels.",
  partners: "World Bank, Punjab Human Capital Development Project",
  status: "Completed",
  serviceLine: ["Advanced Analytics"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census", "Qualitative"],
  confidence: "review"
},
{
  id: "health-lady-health-worker",
  name: "Lady Health Worker Project",
  theme: ["Health"],
  subtheme: [],
  description: "Engaging 300 Lady Health Workers across Lahore, equipped with a custom monitoring application, to study the population they serve and the factors driving their performance, with real-time data shared with the Primary & Secondary Healthcare Department. LHWs serve as Punjab's frontline health changemakers, but the factors behind their successful performance are not well understood despite evidence linking LHW coverage to improved community health indicators. The project will provide household-level data on key health metrics and recommendations to improve LHW performance management province-wide.",
  partners: "IGC, Primary and Secondary Healthcare Department Punjab",
  status: "Ongoing",
  serviceLine: ["Advanced Analytics", "Decision Support Systems"],
  tier2: ["Applied Methods"],
  tier3: ["Survey/Census"],
  confidence: "review"
},
{
  id: "gov-political-incorporation-migrants",
  name: "Political Incorporation of Rural-to-Urban Migrants in Karachi",
  theme: ["Governance"],
  subtheme: [],
  description: "Ran a pilot survey experiment with 1,800 voting-age rural-to-urban migrants in Karachi's Landhi and Kemari constituencies, cross-randomizing identity priming and mobilization messaging ahead of the 2022 local-bodies elections, with actual turnout verified via post-election thumb-ink checks. Internal migrants' political incorporation is understudied despite implications for exclusionary urban planning and informal service-delivery dynamics in fast-growing cities. The pilot tested whether increasing migrants' psychological ownership over Karachi increases their investment in urban political participation.",
  partners: "London School of Economics and Political Science (LSE), Gallup Pakistan",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "econ-day-labor",
  name: "Day Labor Project",
  theme: ["Economic Opportunity"],
  subtheme: ["Labor Markets"],
  description: "Ran a randomized controlled trial with a construction firm in Lahore testing information, incentive, and contractor-supervisor treatments to understand why employers hire day laborers through social networks rather than open spot markets. Roughly 85% of Pakistani construction work is contracted through short-term spot markets riddled with information asymmetries, wage rigidity, and search frictions that increase reliance on social capital over productivity signals. The trial measured how varying the hiring process affects contractor hiring patterns, laborer productivity, and laborers' investment in social versus productive capital.",
  partners: "Private Enterprise Development in Low-Income Countries (PEDL)",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "health-growth-monitoring-tool",
  name: "Growth Monitoring Tool Project",
  theme: ["Health"],
  subtheme: ["Nutrition"],
  description: "Developed and evaluated GroMoTo, a low-cost in-home growth monitoring tool, through an open-label randomized controlled trial in Karachi to address child stunting. Stunting affects 44% of Pakistani children under five and is linked to reduced schooling, adult height, and cognitive skills, yet caregivers in disadvantaged communities rarely receive direct feedback on their children's growth trajectories to act on existing nutritional counseling. The RCT found significant improvements in children's height-for-age z-scores and reduced severe stunting in treatment households one year after baseline, relative to matched controls.",
  partners: "Strategic Impact Evaluation Fund (SIEF), Institute of Economic Research (IER), Shahid Hussain Foundation, National Commission for Human Development, LUMS, Sukoon Water Plant",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: ["RCT"],
  confidence: "review"
},
{
  id: "gov-procurement-efficiency",
  name: "Procurement Efficiency Project",
  theme: ["Governance"],
  subtheme: [],
  description: "Developed a methodology and web portal (Punjab Online Procurement System, POPS) for measuring value-for-money in government procurement, then designed and evaluated a red-tape-reduction intervention for Punjab procurement officers. Government procurement processes lacked systematic tools for measuring efficiency or identifying performance bottlenecks among procurement officers. The intervention generated savings equivalent to roughly 8% of government departmental spending at near-zero cost, with results shared directly with the Chief Minister of Punjab and POPS subsequently mainstreamed across multiple provincial departments.",
  partners: "Punjab Public Procurement Regulatory Authority (PPRA), Punjab Information Technology Board (PITB), Planning and Development Board Punjab, Finance Department Punjab, Punjab Resource Management Program, Higher Education Department Punjab, Agriculture Department Punjab, Health Department Punjab, Communications and Works Department Punjab, IGC, J-PAL",
  status: "Completed",
  serviceLine: ["Decision Support Systems", "Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "review"
},
{
  id: "health-independent-audit-isd",
  name: "Independent Audit of Integrated Service Delivery Interventions in Pakistan",
  theme: ["Health"],
  subtheme: ["Immunization & Vaccines"],
  description: "Conducting independent third-party monitoring of nine Gates Foundation-funded routine immunization and integrated health service interventions across Khyber Pakhtunkhwa, Balochistan, Punjab, and Sindh, combining facility visits, outreach monitoring, mystery shopping, and dashboard-based reporting. Underserved and security-compromised areas face uneven service delivery and low vaccination coverage, requiring unbiased evidence on whether implementation partners meet agreed protocols. Monthly facility visits and quarterly outreach-team monitoring begin in July 2026, comparing self-reported partner data against independently collected field evidence to flag implementation gaps in real time.",
  partners: "Gates Foundation",
  status: "Ongoing",
  serviceLine: ["Evaluations"],
  tier2: ["Process Evaluation"],
  tier3: ["Mixed Methods"],
  confidence: "review"
},
{
  id: "gov-imam-outreach",
  name: "Imam Outreach Project",
  theme: ["Governance", "Health"],
  subtheme: [],
  description: "Surveyed over 100 mosque imams across Punjab to test whether an information intervention could increase compliance with COVID-19 restrictions on congregational Friday prayers, gauging imams' disease knowledge and government messaging trust. Conflicting signals from religious and government authorities on prayer restrictions risked accelerating COVID-19 spread during 2020 lockdowns. Despite roughly 47% of imams holding Friday prayers against government orders, receptiveness to survey information rose from 50% to 80% considering postponement, suggesting imams could serve as a trusted channel for disseminating health and relief-program information.",
  partners: "(none listed)",
  status: "Completed",
  serviceLine: ["Evaluations"],
  tier2: ["Impact Evaluation"],
  tier3: [],
  confidence: "review"
}

];